language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=^6.0
  - ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=^7.0
  - ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=^7.0
  - ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=^7.0
  - ILLUMINATE_VERSION=^6.0  PHPUNIT_VERSION=^7.0

matrix:
  exclude:
    # Laravel 6 does not support PHP 7.1
    - php: 7.1
      env: ILLUMINATE_VERSION=^6.0  PHPUNIT_VERSION=^7.0

dist: xenial
sudo: false

before_install:
  - composer require illuminate/support:${ILLUMINATE_VERSION} --no-update
  - composer require phpunit/phpunit:"${PHPUNIT_VERSION}" --dev --no-update

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - |
    if [ $TRAVIS_BRANCH == 'master' ]; then
        ./vendor/bin/phpunit --coverage-clover=coverage.clover --verbose
    else
        ./vendor/bin/phpunit --coverage-clover=coverage.clover --testsuite=Unit --verbose
    fi

after_script:
  - wget -nv https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
